# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sozdat}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Semyonov"]
  s.date = %q{2009-11-09}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{rotuka@tokak.ru}
  s.executables = ["multiruby", "autotest", "multiruby_setup", "multigem", "zentest", "sozdat", "unit_diff"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/main_controller.rb",
     "app/media/background.png",
     "app/media/icon.png",
     "app/media/logo.png",
     "app/media/logo.svg",
     "app/models/project.rb",
     "app/views/main.ui",
     "bin/autotest",
     "bin/multigem",
     "bin/multiruby",
     "bin/multiruby_setup",
     "bin/sozdat",
     "bin/unit_diff",
     "bin/zentest",
     "config/environment.rb",
     "db/migrate/001_create_projects.rb",
     "lib/sozdat.rb",
     "script/console",
     "test/helper.rb",
     "test/test_sozdat.rb",
     "vendor/gems/cache/ZenTest-4.1.4.gem",
     "vendor/gems/cache/activerecord-2.3.4.gem",
     "vendor/gems/cache/activesupport-2.3.4.gem",
     "vendor/gems/cache/autotest-rails-4.1.0.gem"
  ]
  s.homepage = %q{http://github.com/rotuka/sozdat}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rails IDE from Tokak Studio}
  s.test_files = [
    "test/helper.rb",
     "test/test_sozdat.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

